name: Github Environment
on:
  push:
    branches:
      - test
jobs:
  deployment:
    runs-on: windows-latest
    environment: 
      name: ENV
    steps:
      - name: print secret from environment 
        run: |
          write-host "STAGE_SECRETS:${{ secrets.ENV }}"
    