name: Github Environment
on:
  push:
    branches:
      - test
jobs:
  deployment:
    runs-on: windows-latest
    environment: 
      name: production
    steps:
      - name: print secret from environment 
        run: |
          write-host "production_secret:${{ secrets .production_secret }}"

     