name: passing values to next steps

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  sharing_values:
    runs-on: windows-latest 
    steps:
      # Step 1: Create a variable using $GITHUB_ENV
      - name: Create variable
        shell: pwsh
        run: |
            $output = "hello"
            # Set the environment variable
            "MY_OUTPUT=$output" | Out-File -FilePath $env:GITHUB_ENV -Append

      # Step 2: Use the environment variable in the next step
      - name: Use the variable
        run: |
            Write-Host "The message is: $Env:MY_OUTPUT"


        
     
#   testing:   
    
#     runs-on: windows-latest 
#     steps:
#      - name: command 
#        run:  write-host "edwin" 
#      - name: display the github actor 
#        run : write-host"${{ github.actor }}"
#      - name: use variable from another step 
#        run: |
#           write-host "${{env.My_variable}}"
          
     

