name: passing values to next steps

on:
  push:
    branches:
      - test
  workflow_dispatch:


jobs:
  sharing_values:
    environment: production 
    runs-on: windows-latest 
    steps:
      # Step 1: Create a variable and set an output
      - name: Create variable
        id: step1 
        run: |
          $outputValue = "hello world"
          Write-Host "::set-output name=my_output::$outputValue"
      - name: set the value using ent variable
        run: | 
           write-host "my_variable=helloo world" >> $GITHUB_ENV

        
      # Step 2: Use the variable defined in the previous step
      - name: Use the variable
        run: Write-Host "The message is ${{ steps.step1.outputs.my_output }}"
        
  testing:
    
    runs-on: windows-latest 
    steps:
     - name: command 
       run:  write-host "edwin" 
     - name: display the github actor 
       run : write-host"${{ github.actor }}"
     - name: use variable from another step 
       run: |
          write-host" The message is : $my_variable"
     

