name: passing values to next steps

on:
  push:
    branches:
      - test
  workflow_dispatch:


jobs:
  sharing_values:
  #  environment: production 
    runs-on: windows-latest 
    steps:
      # Step 1: Create a variable using $GIHUB_ENV
      - name: Create variable
        run: |
          $myVariable = "Hello, GitHub Actions!"
          echo "MY_VARIABLE=$myVariable" >> $GITHUB_ENV
          Write-Host "the value of MY_VARIABLE IS : ${{env.MY_VARIABLE}}"

        
     
#   testing:   
    
#     runs-on: windows-latest 
#     steps:
#      - name: command 
#        run:  write-host "edwin" 
#      - name: display the github actor 
#        run : write-host"${{ github.actor }}"
#      - name: use variable from another step 
#        run: |
#           write-host "${{env.My_variable}}"
          
     

