name: passing values to next steps

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  sharing_values:
    runs-on: windows-latest 
    steps:
      # Step 1: Create a variable using $GITHUB_OUTPUT
      - name: Create variable
        id: create_var
        shell: pwsh
        run: |
            $output = "hello"
            # Set the output variable
            "my_output=$output" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

        # Step 2: Use the output variable in the next step
      - name: Use the variable
        run: |
          Write-Host "The message is: ${{ steps.create_var.outputs.my_output }}"
job2:
  try again:
    runs-on: windows-latest
    needs: job1  # Ensure job2 waits for job1 to finish
    steps:
      - name: Use the variable from job1
        run: |
          Write-Host "The message is: $env:MY_OUTPUT"
        shell: pwsh


        
     
