name: passing values to next steps

on:
  push:
    branches:
      - test
  workflow_dispatch:


jobs:
  sharing_values:
  #  environment: production 
    runs-on: windows-latest 
    steps:
      # Step 1: Create a variable using $GIHUB_ENV
      - name: Create variable
        run: |
            $output="hello"
            write-host "$output" | Out-File -FilePath $env:GITHUB_ENV -Append
            Get-Content $Env:GITHUB_ENV
            $output="king"
            Add-Content -Path $env:GITHUB_ENV -Value $output
            Write-Host "new: $env.GITHUB_ENV"

        
     
#   testing:   
    
#     runs-on: windows-latest 
#     steps:
#      - name: command 
#        run:  write-host "edwin" 
#      - name: display the github actor 
#        run : write-host"${{ github.actor }}"
#      - name: use variable from another step 
#        run: |
#           write-host "${{env.My_variable}}"
          
     

